### ISSUE TITLE
Reverse Y axis

### ISSUE THREAD

**Issue by Ghrubo** [halfhp/androidplot#100]
I want to know if its posible to flip Y axis
![imagen](https://user-images.githubusercontent.com/63175679/78505111-d98c2080-7736-11ea-9247-e005fa2b7d91.png)

**Comment by halfhp** [comment]
There's not an automatic way to configure this, but for most use cases (extremely dynamic data could be a little harder) it would be easy to implement using fixed boundaries and custom labels.
