### ISSUE TITLE
Quickstart need an update

### ISSUE THREAD

**Issue by shaielc** [halfhp/androidplot#101]
Quickstart (documentation)  problems:

androidplot: 1.5.7

1. had to add this dependancy in addition to the one already in the quickstart:

`implementation "com.halfhp.fig:figlib:1.0.7"`

2. compile seems to be deprecated for new versions it should be "implementation"

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: ap[

**Comment by halfhp** [comment]
Thanks @shaielc I'll get that corrected!

**Comment by halfhp** [comment]
readme has been updated.  figlib should not be necessary as a separate dependency.
