### ISSUE TITLE
candlesticks are too large in widget

### ISSUE THREAD

**Issue by copypasteearth** [halfhp/androidplot#103]
hello I am making an app widget in android by drawing the chart on a bitmap and the candles are always too large when it is drawn on the canvas. is there some way to adjust the size of the candles, thank you

![Screenshot_20200910-101228](https://user-images.githubusercontent.com/6181334/92743390-7f7b3100-f34e-11ea-9830-d8febb61de13.png)

**Comment by halfhp** [comment]
You can configure the thickness etc of your lines via the [CandlestickFormatter](https://github.com/halfhp/androidplot/blob/f58cd6b43859886a7141d8294c16069d85baf768/androidplot-core/src/main/java/com/androidplot/xy/CandlestickFormatter.java) instance.  You can either pass in your preferred formatting to one of it's constructors or configuring the individual `Paint` instances using it's getters after the fact.
