### ISSUE TITLE
XYPlot in 1.5.7 doesn't show when swiping back in ViewPager2 

### ISSUE THREAD

**Issue by yf13** [halfhp/androidplot#104]
I am trying to use XYPlot in a fragment managed by ViewPager2.

When set RenderMode to use background thread, I can see the charts only upon the first enter of the fragment. This means after swiping to another fragment and swipe back, the plots are empty. I have another TextView which is still visible.

Then when I changed the RenderMode to use main thread, I can see the XYPlot when swiping back to the containing fragment.

There is no crash or any logs.

**Comment by halfhp** [comment]
Hi @yf13  thanks for the bug report - would it be possible to get some sample code that triggers this issue?

**Comment by tjohnn** [comment]
@halfhp This is an issue with using androidplot in recyclerviews generally, I created a simple sample where I regenrated the issue https://github.com/tjohnn/androidplot-in-recyclerview-issue

**Comment by halfhp** [comment]
Fixed in [this PR](https://github.com/halfhp/androidplot/pull/113)

Will be available in version 1.5.9.
