### ISSUE TITLE
renderMode attribute always sets to use_background_thread

### ISSUE THREAD

**Issue by ajprieger** [halfhp/androidplot#107]
In the renderMode attribute for graph widgets, both use_background_thread and use_main_thread have the value 0, which causes setting the value to either of them to use the background thread. Not setting the attribute at all causes it to properly default to main thread, but explicitly setting it to main thread doesn't work.

**Comment by halfhp** [comment]
Just to make sure I'm understanding, you're saying this issue occurs when there is more than one graph widget on the same screen?

**Comment by ajprieger** [comment]
No, it happens with only one graph widget. It's just anytime you set render mode to use_main_thread, it actually sets it to background thread mode.

**Comment by halfhp** [comment]
Thanks for the report - fix here: https://github.com/halfhp/androidplot/pull/111

will be available in version 1.5.9.
