### ISSUE TITLE
figlib not available on mavenCentral (in contrast to jcenter)

### ISSUE THREAD

**Issue by berndporr** [halfhp/androidplot#109]
* Description of the problem
  jcenter is going to be shut down and there is a new repository called "mavenCentral()". With jcenter() it no longer compiles because figlib 1.0.7 is missing.
* Steps to reproduce the issue
  Replace jcenter() by mavenCentral() in build.gradle. Throws up then the error: Could not find com.halfhp.fig:figlib:1.0.7.
* Version(s) of Androidplot being used: com.androidplot:androidplot-core:1.5.7

A workaround is to just have both jcenter() and mavenCentral() in the build.gradle for now. Of course not ideal but will be OK for another 6 months till jcenter() will be shut down.

**Comment by lokesh-sudhakar** [comment]
jcenter() is obsolete now. what is the workaround
@berndporr

**Comment by halfhp** [comment]
Figlib has been updated to be hosted on Github Packages now - see the notes in the updated readme -https://github.com/halfhp/fig
