### ISSUE TITLE
Graph is finnicky about size

### ISSUE THREAD

**Issue by Erhannis** [halfhp/androidplot#16]
I've been struggling to get the graph to show up consistently.  wrap_content doesn't work, which I guess makes some sense.  When I use a scrollview, for when my other views take up too much space, match_parent shrinks the graph to nothing, which also makes some sense.  Less sensical is that when I set the graph to be 1138dp wide or wider, the graph doesn't show up at all - there's just a big white empty space the same size as the graph ought to be.  Similar things appear to happen for height.  I think the specific thresholds may be specific to screen, device, or layout.

In an attempt to get a consistently non-weird size, I've wrapped the graph in a PercentRelativeLayout.  Which...I think wasn't working but now apparently is?  Not sure I trust it, yet, but it's working for now.

**Comment by halfhp** [comment]
Hmm, sounds like you might be dealing with [this issue](https://groups.google.com/forum/#!topic/androidplot/Wjbv0DSeUTg).

**Comment by Erhannis** [comment]
Ah.  No, I see a warning, now: "W/View: View too large to fit into drawing cache, needs 19200000 bytes, only 16384000 available".  So...that's a thing.  It kindof explains why it was so erratic in happening.

**Comment by halfhp** [comment]
> When I use a scrollview, for when my other views take up too much space, match_parent shrinks the graph to nothing, which also makes some sense. Less sensical is that when I set the graph to be 1138dp wide or wider, the graph doesn't show up at all - there's just a big white empty space the same size as the graph ought to be. Similar things appear to happen for height.

You probably want to be using match_parent for width and only specifying a fixed height for the plot.  There's actually a [code example](https://github.com/halfhp/androidplot/blob/master/demoapp/src/main/java/com/androidplot/demos/ListViewActivity.java) of a listview of plots in the DemoApp that does this. (Listview is scrollable)  This is the listview item xml it's using:

```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:ap="http://schemas.android.com/apk/res-auto"
              android:layout_width="fill_parent"
              android:layout_height="fill_parent">

    <com.androidplot.xy.XYPlot
            style="@style/APDefacto.Light"
            android:id="@+id/xyplot"
            android:layout_width="fill_parent"
            android:layout_height="250dp"
            ap:title="an xy plot"/>

</LinearLayout>
```

As far as the memory issue you're seeing, it kind of sounds like the visible dimensions of the plot is being calculated to be enormous.  I'd expect that has something to do with how the plot is being placed into the scrollview.

**Comment by Erhannis** [comment]
Long story short, I suspect the key is "if the plot is any bigger than the screen, it won't render".  For several reasons in turn, that's what I was getting, whether or not I had a ScrollView.  Each limitation kinda makes sense, but when I moved from one to another without realizing it, the primary symptom was still just that there was no graph, which was confusing.  I think I've worked out the problems on my end, anyway, and each of the underlying problems are debatably not actually issues, so it's up to you if you want to close this or not.  It might be good to have something in the docs saying A) if you're using scrollview, you have to specify a specific height for the plot.  PercentRelativeLayout might be a good choice.  And B) if the plot's area exceeds that of the screen, it will be invisible.

**Comment by halfhp** [comment]
The issue with plot area exceeding screen area is actually an interesting / unexpected detail.  Going to look into that to start.

**Comment by halfhp** [comment]
closing for now.  if this becomes a stumbling block for others we can be reopened.
