### ISSUE TITLE
PanZoom doesn't mix well with ScrollView

### ISSUE THREAD

**Issue by Erhannis** [halfhp/androidplot#18]
If you have a PanZoom on a plot in a ScrollView, they don't play too nicely together.  You can pan for half an inch or so, but once you reach the limit where the scrollview would normall scroll, it does so, and the plot stops panning.  It kinda works, and it could be worse, but it'd be a lot nicer if the graph panned when you dragged on the plot itself (as opposed to the legend, perhaps), and it the graph couldn't pan further in that direction, the scrollview scrolled instead.

**Comment by halfhp** [comment]
Hmm I'm going to have to think about this one a bit.  

Nesting elements that share one or more scrollable axis is something that google has historically discouraged, although they have more recently provided a [NestedScrollView component](https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html) has been made available. 

I'll get back to you on this one :)

**Comment by Erhannis** [comment]
Yeah, I've tried to nest scrollviews before.  XP  I hadn't heard about NestedScrollView, yet; neat.  Stab in the dark: under the assumption that NestedScrollView works like it ought to, maybe you could borrow from it so that the plot would pan nicely inside of a NestedScrollView, if not an ordinary ScrollView?

**Comment by halfhp** [comment]
Possibly :) Androidplot's pan/zoom logic is pretty different than Android's scrolling logic so it's hard to say how well they can be made to play together.  It's worth a try, but it's low on my priority list at the moment.  If someone else wants to give it a shot, contributions are welcome :-)
