### ISSUE TITLE
setDrawRangeOriginEnabled w/o effect

### ISSUE THREAD

**Issue by semaphore3000** [halfhp/androidplot#4]
setDrawRangeOriginEnabled and setDrawDomainOriginEnabled are both without effect in AP 1.1.0. The values set are never read.

**Comment by halfhp** [comment]
You are correct sir -  these will be removed in the next release.  

How to alter range / domain origin styling in 1.1.0:

**Programmatically:**

`plot.getGraph().setRangeOriginLinePaint(somePaint);`

**XML:**

```
ap:rangeOriginLineThickness="2dp"
ap:domainOriginLineThickness="2dp"
ap:domainOriginLineColor="@color/red"
ap:rangeOriginLineColor="@color/red"
```

**Comment by halfhp** [comment]
Androidplot 1.2.1 has been released and includes this fix.
