### ISSUE TITLE
Charts display previous data when used in ListView adapter

### ISSUE THREAD

**Issue by mslavkovski** [halfhp/androidplot#51]
When chart control is used in listview all elements of the list that include charts are having the same values as the first item although the data is fed correctly.

**Comment by halfhp** [comment]
There is not enough information provided to do anything with.  Additionally there is a working example of a ListView of XYPlots in the DemoApp, so it seems probable that this is not a bug.

Feel free to attach a sample project that reproduces the bug and I'll reopen to investigate further.

**Comment by mslavkovski** [comment]
It seems that I was calling the .invalidate() method, not the .redraw(). It's all good now.
Thanks.
