### ISSUE TITLE
NaNs not supported

### ISSUE THREAD

**Issue by mxk** [halfhp/androidplot#56]
The following code results in an plot that only shows vertices, but no lines or shading:

```java
plot.addSeries(new SimpleXYSeries(
		Arrays.asList(new Float[]{0f, 1f, 2f, 3f, 4f}),
		Arrays.asList(new Float[]{5f, 6f, Float.NaN, 4f, 2f}),
		"Data"
), new LineAndPointFormatter());
```

Replacing Float.NaN with any finite value fixes the problem. Ideally, NaNs should cause a break in the rendered line. For this dataset, I would expect to see two line segments with a break in between.

I'll see if I can implement my own renderer that does this, but I'm also not clear on the expected behavior of FastXYSeries interface when there are NaNs in the data. If all Y values are NaN, should the RectRegion Y min/max be NaN or null? The latter would simplify some of the code, but I don't know if it's acceptable to have an undefined min/max with a series size() > 0.

**Comment by halfhp** [comment]
In the case of `FastLineAndPointRenderer`, the limiting effect of `NaN `would be equivalent to that of null values, which as per the javadoc are not supported.  The main issue is allowing nulls into the dataset would invalidate the assumptions `FastLineAndPointRenderer` makes for the sake of performance. 

In the case of all `NaN` values etc. there is essentially no resolution in the data for Androidplot to use to calculate min/max.  You could try specifying your own domain and range boundaries but the result would be undefined.

As far as introducing breaks in your data for non-values, null should be used in place of `NaN`, along with a renderer that supports nulls such as `LineAndPointRenderer`.

**Comment by mxk** [comment]
Thanks for the quick reply! So basically, I will replace NaNs with nulls in my data, but then for the all-null case, would it be better for FastXYSeries implementation to return a RectRegion that has undefined Y min/max and set plot Y boundaries manually, or to provide some default min/max values?

**Comment by halfhp** [comment]
For `FastXYSeries` it should be ok to return null from `minMax()` but this will cause Androidplot to iterate over each point in the series manually to attempt to discover what you already know; that there's no resolution in the data.  Setting boundaries on the plot should handle this scenario visually but from an efficiency perspective it would be better to return a non-null default from `minMax()` and prevent the pointless iteration step mentioned above.

Also don't forget to use something besides FastLineAndPointRenderer (or you can extend it for your needs) as it [does not support null vals](https://159-1424783-gh.circle-artifacts.com/0/tmp/circle-artifacts.WaDbp0p/javadoc/index.html).

**Comment by halfhp** [comment]
Closing this for now since it sounds like theres no bug.  Feel free to reopen if that's not the case.
