### ISSUE TITLE
Duplicated attributes from AppCompat

### ISSUE THREAD

**Issue by mttpl** [halfhp/androidplot#6]
Antroidplot uses two attributes: title and titleTextColor which are already defined in AppCompat library.
This means that you simply cannot use Antroidplot >=1.0 in projects where AppCompat is required.

**Comment by halfhp** [comment]
What version of  of build tools are you using?  Upgrading to 24.0.2 may resolve the issue as this seems very similar to [this issue](http://stackoverflow.com/questions/39184283/attribute-title-has-already-been-define-when-have-android-plot-dependencies-1/39192731#39192731).

**Comment by halfhp** [comment]
Local testing confirms that upgrading build tools to 24.0.2 resolve the issue.  Closing
