### ISSUE TITLE
XYGraphWidget.seriesToScreenY converts incorrectly

### ISSUE THREAD

**Issue by guycnicholas** [halfhp/androidplot#61]
`    protected float seriesToScreenY(Number y) {
        return (float) plot.getBounds().getyRegion().
                transform(y.doubleValue(), gridRect.left, gridRect.right, true);
    }
`
In the above code, this is a Y coordinate conversion, so the min/max values should be gridRect.bottom/top not left/right

https://github.com/halfhp/androidplot/blob/0cb45aef633bc64fcaf4eca17c5b1ffd454f350f/androidplot-core/src/main/java/com/androidplot/xy/XYGraphWidget.java#L492

**Comment by guycnicholas** [comment]
In looking at the tests I think the problem is all the related tests use a region with similar XY dimensions, so the conversions work. i.e.
    public void testSeriesToScreenY() throws Exception {
        when(xyPlot.getBounds()).thenReturn(new RectRegion(-100, 100, -100, 100));
I believe this whole series of tests should really use a rectangle with different XY starting values and sizes.

**Comment by halfhp** [comment]
I've merged your fix into master.  Thanks for the contribution!
