### ISSUE TITLE
Cannot resize a SimpleXYSeries if it's a Y values only format

### ISSUE THREAD

**Issue by matdev** [halfhp/androidplot#69]
Hello

Your library looks great !

I just noticed that calling the SimpleXYSeries.resize() throws a NullPointerException if the serie is using Y_VALS_ONLY format.

I would be neat if resize() would work also with Y_VALS_ONLY series.

Cheers
Mathias

**Comment by halfhp** [comment]
Thanks for the report @matdev!  I should be able to get this fixed in the next release.

**Comment by halfhp** [comment]
Fixed in the current PR up for 1.5.4.  Stay tuned for a release!
