### ISSUE TITLE
Old API documentation coming up in Google

### ISSUE THREAD

**Issue by matdev** [halfhp/androidplot#70]
Most of the time when I'm looking for some doc about AndroidPlot, an old API doc comes up.
For instance, if you search for BoundaryMode androidplot in Google, you will get the following link first:
http://androidplot.com/javadoc/0.5.1/com/androidplot/xy/BoundaryMode.html

Nothing about the new 1.5.3 version.

Could please tell Google when a page is out of date ? 
maybe using the "noindex" metatag

**Comment by halfhp** [comment]
Thanks for the report @matdev.  I'm in the process of updating the robots rules to remove a good chunk of the old/obsolete content.
