### ISSUE TITLE
Graph doesn't resize when layout size changes

### ISSUE THREAD

**Issue by 195024** [halfhp/androidplot#73]
I set an onTouchListener on the XYPlot to hide my LinearLayout with buttons (let's call it controlPanel) so there would be more space for the graph, but once the controlPanel is gone, the plot fills the new available height and yet the graph stays at the same size. Please look at the screens and you'll know what my issue is. I tried calling plot.redraw() and plot.getGraph.refreshLayout() after changing controlPanel's visibility but to no effect. The graph resizes itself correctly when I make the controlPanel gone and change orientation and viceversa (of course I'm saving the controlPanel's state to keep the visibility status).
![screenshot_20180221-115349](https://user-images.githubusercontent.com/23454134/36476845-5869dfc2-16ff-11e8-9cbc-7016cadce901.jpg)
![screenshot_20180221-115353](https://user-images.githubusercontent.com/23454134/36476846-588cec06-16ff-11e8-8966-17e41290936b.png)

**Comment by halfhp** [comment]
Thanks for the report - I'm looking into this

**Comment by halfhp** [comment]
The fix will be going out with 1.5.4

**Comment by 195024** [comment]
Nice, when is the 1.5.4 coming out? I need this to work, Is there any temporary solution you could provide me with for now?

**Comment by halfhp** [comment]
> Nice, when is the 1.5.4 coming out? 

Should be available sometime tomorrow morning.

> Is there any temporary solution you could provide me with for now?

You'd need to extend XYGraphWidget and then swap out the default instance with an instance of your implementation.  If you look in `XYGraphWidget.doOnDraw()` there are a couple lines that init gridRect and labelRect if null.  Basically that needs to happen any time the dimensions of the passed in `RectF` change.

**Comment by halfhp** [comment]
1.5.4 has been pushed to maven central and should be available any time now.

**Comment by 195024** [comment]
Lovely, thanks for your hard work!
