### ISSUE TITLE
Method Canvas.save(int) has been removed from Android SDK (API 28)

### ISSUE THREAD

**Issue by AnthonyStephan** [halfhp/androidplot#80]
My app uses Android Plot for a simple XY plot (lines).

Just updated to API 28 (targetSdkVersion and compileSdkVersion)

It does not build anymore, see the output:

Warning: com.androidplot.pie.PieRenderer: can't find referenced method 'int save(int)' in library class android.graphics.Canvas
Warning: com.androidplot.ui.LayoutManager: can't find referenced method 'int save(int)' in library class android.graphics.Canvas
Warning: com.androidplot.ui.SeriesRenderer: can't find referenced method 'int save(int)' in library class android.graphics.Canvas
Warning: com.androidplot.ui.widget.TextLabelWidget: can't find referenced method 'int save(int)' in library class android.graphics.Canvas
Warning: com.androidplot.xy.LineAndPointRenderer: can't find referenced method 'int save(int)' in library class android.graphics.Canvas
Warning: com.androidplot.xy.XYGraphWidget: can't find referenced method 'int save(int)' in library class android.graphics.Canvas

In fact Canvas.save(int) has been removed from the SDK in API 28. In was deprecated since 28, now it is fully removed and you should call Canvas.save() instead

**Comment by halfhp** [comment]
Thx @AnthonyStephan - will get this resolved ASAP

**Comment by AnthonyStephan** [comment]
Great, thank you @halfhp for your great work :) 
Don't be in a hurry, only a few devices have access to Android P for the moment ;)

**Comment by halfhp** [comment]
Fixed in 1.5.6

**Comment by AnthonyStephan** [comment]
Hello Nick,

Thank a lot for your reactivity! V1.5.6 will be integrate ASAP in Printoid
for OctoPrint
