### ISSUE TITLE
Android 9 compiler warnings

### ISSUE THREAD

**Issue by pwireless** [halfhp/androidplot#93]
Thank you very much for the great library!

I downloaded the latest code from github, and changed the targetSdk to 28.

I get the following warnings from Android Gradle Plugin.

Could you possibly update the code to remove these warnings? Thank you

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. |  
-- | --
Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'. |  
Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'. |  
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. |  
Configuration 'debugCompile' is obsolete and has been replaced with 'debugImplementation' and 'debugApi'. |  
Configuration 'releaseCompile' is obsolete and has been replaced with 'releaseImplementation' and 'releaseApi'. |  
Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'. |  
Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'. |

**Comment by halfhp** [comment]
@pwireless yep will try to get that updated in the next release.  PR's are welcome if you need it sooner :)

**Comment by halfhp** [comment]
fixed in 1.5.7
